version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Building the Spring Boot application..."
  post_build:
    commands:
      - echo "Packaging the Spring Boot application..."
      - mvn -Prelease-nacos -Dmaven.test.skip=true -Drat.skip=true clean install -U
      - zip -j  backend-pkg.zip distribution/target/nacos-server-2.3.0/nacos/* aws/java/*
artifacts:
  files:
    - backend-pkg.zip
    - aws/java/appspec.yml
    - aws/java/startup.sh
    - aws/java/before-install.sh
    - aws/java/after-install.sh
  discard-paths: yes
cache:
  paths:
    - .m2/repository/